// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRA8sasF_K4wir0qu1UTzuLh0ca7lGjco',
    appId: '1:614372402994:web:0fea54f18916f8a28b592b',
    messagingSenderId: '614372402994',
    projectId: 'early-career-assistance-app',
    authDomain: 'early-career-assistance-app.firebaseapp.com',
    storageBucket: 'early-career-assistance-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVZ0Uu-h3ktNDf-SdG3kMQM0__taT3_Y',
    appId: '1:614372402994:android:a5904a8bd8c95da08b592b',
    messagingSenderId: '614372402994',
    projectId: 'early-career-assistance-app',
    storageBucket: 'early-career-assistance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Ici-VsfCLDLfcqn-b6CvfYL11L_OtrE',
    appId: '1:614372402994:ios:ee7e6860564a9d468b592b',
    messagingSenderId: '614372402994',
    projectId: 'early-career-assistance-app',
    storageBucket: 'early-career-assistance-app.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Ici-VsfCLDLfcqn-b6CvfYL11L_OtrE',
    appId: '1:614372402994:ios:ee7e6860564a9d468b592b',
    messagingSenderId: '614372402994',
    projectId: 'early-career-assistance-app',
    storageBucket: 'early-career-assistance-app.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRA8sasF_K4wir0qu1UTzuLh0ca7lGjco',
    appId: '1:614372402994:web:3e99cf67eb5073ed8b592b',
    messagingSenderId: '614372402994',
    projectId: 'early-career-assistance-app',
    authDomain: 'early-career-assistance-app.firebaseapp.com',
    storageBucket: 'early-career-assistance-app.firebasestorage.app',
  );

}